version: 2

before:
  hooks:
    # Generate BAML client before building
    - baml-cli generate
    # Run tests
    - go test ./...
    # Run linter
    - go vet ./...

builds:
  - id: gavel
    main: ./cmd/gavel
    binary: gavel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore combinations that don't make sense
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: gavel
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: chris-regnier
    name: gavel
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Gavel {{ .Tag }}

    AI-powered code analysis with structured SARIF output for CI/CD workflows.
  footer: |
    ## Installation

    Download the appropriate binary for your platform from the assets below.

    **Full Changelog**: https://github.com/chris-regnier/gavel/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap (optional, uncomment if you create a tap)
# brews:
#   - name: gavel
#     repository:
#       owner: chris-regnier
#       name: homebrew-tap
#     homepage: https://github.com/chris-regnier/gavel
#     description: "AI-powered code analysis with structured output"
#     license: MIT
#     install: |
#       bin.install "gavel"

# Docker images (optional, uncomment if you want Docker releases)
# dockers:
#   - image_templates:
#       - "ghcr.io/chris-regnier/gavel:{{ .Tag }}"
#       - "ghcr.io/chris-regnier/gavel:v{{ .Major }}"
#       - "ghcr.io/chris-regnier/gavel:v{{ .Major }}.{{ .Minor }}"
#       - "ghcr.io/chris-regnier/gavel:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
