version: '3'

vars:
  BINARY: gavel

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build -o {{.BINARY}} ./cmd/gavel

  test:
    cmds:
      - go test ./... -v

  generate:
    cmds:
      - baml-cli generate

  lint:
    cmds:
      - go vet ./...
