// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type FindingClassView struct {
	inner baml.ClassBuilder
}

func (t *FindingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FindingClassView) PropertyRuleId() (ClassPropertyView, error) {
	return t.inner.Property("ruleId")
}

func (t *FindingClassView) PropertyLevel() (ClassPropertyView, error) {
	return t.inner.Property("level")
}

func (t *FindingClassView) PropertyMessage() (ClassPropertyView, error) {
	return t.inner.Property("message")
}

func (t *FindingClassView) PropertyFilePath() (ClassPropertyView, error) {
	return t.inner.Property("filePath")
}

func (t *FindingClassView) PropertyStartLine() (ClassPropertyView, error) {
	return t.inner.Property("startLine")
}

func (t *FindingClassView) PropertyEndLine() (ClassPropertyView, error) {
	return t.inner.Property("endLine")
}

func (t *FindingClassView) PropertyRecommendation() (ClassPropertyView, error) {
	return t.inner.Property("recommendation")
}

func (t *FindingClassView) PropertyExplanation() (ClassPropertyView, error) {
	return t.inner.Property("explanation")
}

func (t *FindingClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *TypeBuilder) Finding() (*FindingClassView, error) {
	bld, err := t.inner.Class("Finding")
	if err != nil {
		return nil, err
	}
	return &FindingClassView{inner: bld}, nil
}

func (t *FindingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
