// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Finding struct {
	RuleId         string  `json:"ruleId"`
	Level          string  `json:"level"`
	Message        string  `json:"message"`
	FilePath       string  `json:"filePath"`
	StartLine      int64   `json:"startLine"`
	EndLine        int64   `json:"endLine"`
	Recommendation string  `json:"recommendation"`
	Explanation    string  `json:"explanation"`
	Confidence     float64 `json:"confidence"`
}

func (c *Finding) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Finding" {
		panic(fmt.Sprintf("expected Finding, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "ruleId":
			c.RuleId = baml.Decode(valueHolder).Interface().(string)

		case "level":
			c.Level = baml.Decode(valueHolder).Interface().(string)

		case "message":
			c.Message = baml.Decode(valueHolder).Interface().(string)

		case "filePath":
			c.FilePath = baml.Decode(valueHolder).Interface().(string)

		case "startLine":
			c.StartLine = baml.Decode(valueHolder).Int()

		case "endLine":
			c.EndLine = baml.Decode(valueHolder).Int()

		case "recommendation":
			c.Recommendation = baml.Decode(valueHolder).Interface().(string)

		case "explanation":
			c.Explanation = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Float()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Finding", key))

		}
	}

}

func (c Finding) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["ruleId"] = c.RuleId

	fields["level"] = c.Level

	fields["message"] = c.Message

	fields["filePath"] = c.FilePath

	fields["startLine"] = c.StartLine

	fields["endLine"] = c.EndLine

	fields["recommendation"] = c.Recommendation

	fields["explanation"] = c.Explanation

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("Finding", fields, nil)
}

func (c Finding) BamlTypeName() string {
	return "Finding"
}
