// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{

	"analyze.baml":    "class Finding {\n  ruleId string @description(\"The policy name this finding relates to\")\n  level string @description(\"One of: error, warning, note, none\")\n  message string @description(\"Concise description of the issue\")\n  filePath string @description(\"Path to the file containing the issue\")\n  startLine int @description(\"Line number where the issue starts\")\n  endLine int @description(\"Line number where the issue ends\")\n  recommendation string @description(\"Suggested fix or action\")\n  explanation string @description(\"Longer reasoning about why this is an issue\")\n  confidence float @description(\"0.0 to 1.0, how confident you are in this finding\")\n}\n\nfunction AnalyzeCode(\n  code: string,\n  policies: string,\n  personaPrompt: string,\n  additionalContext: string\n) -> Finding[] {\n  client OpenRouter\n  prompt #\"\n    {{ personaPrompt }}\n\n    {% if additionalContext != \"\" %}\n    ===== ADDITIONAL CONTEXT =====\n    The following context may be relevant to your analysis:\n\n    {{ additionalContext }}\n\n    ===== END CONTEXT =====\n    {% endif %}\n\n    ===== POLICIES TO CHECK =====\n    Analyze the code against these specific policies. Only report genuine violations.\n    If a policy doesn't apply to this code, don't force a finding.\n\n    {{ policies }}\n\n    ===== CODE TO ANALYZE =====\n    {{ code }}\n\n    ===== INSTRUCTIONS =====\n    For each policy violation or issue you find:\n    1. Identify the exact line numbers where it occurs\n    2. Write a concise message (one sentence)\n    3. Provide a detailed explanation following your persona's tone\n    4. Suggest a specific, actionable recommendation\n    5. Assign an appropriate confidence level based on the guidance above\n\n    Only report genuine issues. Quality over quantity.\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
	"clients.baml":    "// OpenRouter client for gavel analysis\nclient<llm> OpenRouter {\n  provider \"openai-generic\"\n  retry_policy Exponential\n  options {\n    base_url \"https://openrouter.ai/api/v1\"\n    api_key env.OPENROUTER_API_KEY\n    model \"anthropic/claude-sonnet-4\"\n  }\n}\n\n// Ollama client for local LLM analysis\nclient<llm> Ollama {\n  provider \"openai-generic\"\n  retry_policy Exponential\n  options {\n    base_url env.OLLAMA_BASE_URL\n    model env.OLLAMA_MODEL\n  }\n}\n\n// Anthropic client for Claude API\nclient<llm> Anthropic {\n  provider \"anthropic\"\n  retry_policy Exponential\n  options {\n    api_key env.ANTHROPIC_API_KEY\n    model env.ANTHROPIC_MODEL\n  }\n}\n\n// AWS Bedrock client for Claude models on Bedrock\nclient<llm> Bedrock {\n  provider \"aws-bedrock\"\n  retry_policy Exponential\n  options {\n    region env.BEDROCK_REGION\n    model env.BEDROCK_MODEL\n  }\n}\n\n// OpenAI client for GPT models\nclient<llm> OpenAI {\n  provider \"openai\"\n  retry_policy Exponential\n  options {\n    api_key env.OPENAI_API_KEY\n    model env.OPENAI_MODEL\n  }\n}\n\nretry_policy Exponential {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 10000\n  }\n}\n",
	"generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"go\", \"rust\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"go\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.218.1\"\n\n    // 'baml-cli generate' will run this after generating go code\n    // This command will be run from within $output_dir/baml_client\n    on_generate \"gofmt -w . && goimports -w .\"\n\n    // Your Go packages name as specified in go.mod\n    // We need this to generate correct imports in the generated baml_client\n    client_package_name \"github.com/chris-regnier/gavel\"\n}\n",
}

func getBamlFiles() map[string]string {
	return file_map
}
