// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/chris-regnier/gavel/baml_client/stream_types"
	"github.com/chris-regnier/gavel/baml_client/types"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsError   bool
	Error     error
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() *TFinal {
	return s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() *TStream {
	return s.as_stream
}

// / Streaming version of AnalyzeCode
func (*stream) AnalyzeCode(ctx context.Context, code string, policies string, personaPrompt string, additionalContext string, opts ...CallOptionFunc) (<-chan StreamValue[[]stream_types.Finding, []types.Finding], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"code": code, "policies": policies, "personaPrompt": personaPrompt, "additionalContext": additionalContext},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeCode: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeCode", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[[]stream_types.Finding, []types.Finding])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[[]stream_types.Finding, []types.Finding]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).([]types.Finding)
				channel <- StreamValue[[]stream_types.Finding, []types.Finding]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).([]stream_types.Finding)
				channel <- StreamValue[[]stream_types.Finding, []types.Finding]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateConfig
func (*stream) GenerateConfig(ctx context.Context, requirements string, preferred_provider string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.GeneratedConfig, types.GeneratedConfig], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"requirements": requirements, "preferred_provider": preferred_provider},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateConfig: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateConfig", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.GeneratedConfig, types.GeneratedConfig])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.GeneratedConfig, types.GeneratedConfig]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.GeneratedConfig)
				channel <- StreamValue[stream_types.GeneratedConfig, types.GeneratedConfig]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.GeneratedConfig)
				channel <- StreamValue[stream_types.GeneratedConfig, types.GeneratedConfig]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GeneratePersona
func (*stream) GeneratePersona(ctx context.Context, description string, focus_areas []string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.GeneratedPersona, types.GeneratedPersona], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"description": description, "focus_areas": focus_areas},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GeneratePersona: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GeneratePersona", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.GeneratedPersona, types.GeneratedPersona])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.GeneratedPersona, types.GeneratedPersona]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.GeneratedPersona)
				channel <- StreamValue[stream_types.GeneratedPersona, types.GeneratedPersona]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.GeneratedPersona)
				channel <- StreamValue[stream_types.GeneratedPersona, types.GeneratedPersona]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GeneratePolicy
func (*stream) GeneratePolicy(ctx context.Context, description string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.GeneratedPolicy, types.GeneratedPolicy], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"description": description},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GeneratePolicy: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GeneratePolicy", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.GeneratedPolicy, types.GeneratedPolicy])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.GeneratedPolicy, types.GeneratedPolicy]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.GeneratedPolicy)
				channel <- StreamValue[stream_types.GeneratedPolicy, types.GeneratedPolicy]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.GeneratedPolicy)
				channel <- StreamValue[stream_types.GeneratedPolicy, types.GeneratedPolicy]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateRule
func (*stream) GenerateRule(ctx context.Context, description string, category string, languages string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.GeneratedRule, types.GeneratedRule], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"description": description, "category": category, "languages": languages},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateRule: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateRule", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.GeneratedRule, types.GeneratedRule])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.GeneratedRule, types.GeneratedRule]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.GeneratedRule)
				channel <- StreamValue[stream_types.GeneratedRule, types.GeneratedRule]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.GeneratedRule)
				channel <- StreamValue[stream_types.GeneratedRule, types.GeneratedRule]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}
